### ISSUE TITLE
Link to url fragment on same page not supported

### ISSUE THREAD

**Issue by dschulten** [winterstein/Eclipse-Markdown-Editor-Plugin#47] opened 2014-07-27 08:42 UTC
Links to url fragments on the same page are not supported.

When I write

```
## Foo Heading
```
and refer to it using 
```
see [above](#foo-heading)
```
it is valid Github Flavored Markdown because GFM automatically inserts anchors for headings (lowercase with hyphens for blanks, punctuation removed). However the editor complains "Cannot resolve element with id ''

In standard md it seems you have to provide an anchor above the heading to make this work, as shown below.

```
<a name="foo-heading"></a>
## Foo Heading
```
The latter does not work either, even if I use the id attribute.

It is particularly annoying that in Eclipse this is considered an error, so the project gets a red-cross icon, and one cannot even disable validation.

The ideal solution would be to make this work for GFM as well as plain markdown. One more argument for a GitHub flavour mode, see #41

**Comment by paulvi** [comment] 2015-01-12 08:20
close as duplicate of #17

**Closed by paulvi** 2015-01-12 08:20 UTC
